import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Article } from './article';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const articles = [
      { id: 1, title: 'Anaphylaxis and emergency: Regional data in Lorraine and management', authors: 'J Corriger, E Beaudouin, C Rothmann, E Penven, Q Haumonte, H Thomas, J Picaud, V M Nguyen-Grosjean, J Corriger-Ippolito, F Braun, M De Talancé, B Auburtin, P Atain-Kouadio, A Borsa-Dorion, D Baugnon, M De Carvalho, R Jaussaud, P L Nguyen-Thi, P E Bollaert', abstract: 'Anaphylaxis is an allergic emergency, and its frequency increases in all countries since the 2000s. Epinephrine administration and allergist-emergency room interactions are the key points of its management. The objective of the study was to determine the incidence of anaphylaxis in 2015, to describe its main characteristics and to evaluate practices in Lorraine for this period. Four hospitals in Lorraine were selected. Medical records from each center\'s adult and pediatric emergency rooms, from 1st January to 31th December 2015, were classified based on their admission cause and diagnosis code. When data were consistent for an anaphylaxis (95 selected ICD-10 codes) record was analyzed by an allergist practitioner and included if confirmed. Epidemiological data, clinical characteristics, management assessment and orientation were provided through a standardized questionnaire. Anaphylaxis is responsible for 0.16% emergency rooms’ admissions in the participating centers in 2015; the estimated incidence in Lorraine is 34 per 100,000 person-years. Clinical presentation depends on age, etiologic agent, several cofactors (asthma, cardiovascular comorbidities, treatments) and reaction\'s gravity. When anaphylaxis was serious (Ring-Messmer\'s grade ≥ 3), epinephrine use was only 32.4% (48/148) and observation duration was less than 6 hours 4 times on 10. An allergist referral was proposed in 57.9% (187/323) patients. Anaphylaxis is not a rare cause for emergency rooms’ admission in Lorraine. Therefore guidelines are insufficiently followed and a better knowledge of the pathology and its management is necessary for emergency healthcare practitioners.' },
      { id: 2, title: 'Epidemiological Data on Anaphylaxis in French Emergency Departments', authors: 'J Corriger, E Beaudouin, C Rothmann, E Penven, Q Haumonte, H Thomas, J Picaud, V M Nguyen-Grosjean, J Corriger-Ippolito, F Braun, M De Talancé, B Auburtin, P Atain-Kouadio, A Borsa-Dorion, D Baugnon, M De Carvalho, R Jaussaud, P L Nguyen-Thi, P E Bollaert, P Demoly, L K Tanno', abstract: 'Background: Although anaphylaxis has been considered a priority public health issue in the world allergy community, epidemiological data on morbidity and mortality remain suboptimal. We performed the first multicenter epidemiological study in French emergency departments (EDs). The study covered 7 EDs over a period of 1 year. The objectives were to identify areas that are amenable to change and to support ongoing national and international efforts for better diagnosis, management, and prevention of anaphylaxis. Methods: Ours was a descriptive study based on data routinely reported to French institutional administrative databases from 7 French public health institutions in the Lorraine region between January and December 2015. Data were collected based on the anaphylaxisrelated codes of the International Classification of Diseases (ICD)-10, and cases were clinically validated as anaphylaxis. Results: Of the 202 079 admissions to the EDs, 4817 had anaphylaxis-related codes; of these, 323 were clinically validated as anaphylaxis. Although 45.8% were severe, adrenaline was prescribed in only 32.4% of cases. Of the 323 cases, 57.9% were subsequently referred for an allergy work-up or evaluation (after or during hospitalization), and 17.3% were prescribed autoinjectable epinephrine. Conclusion: Our results highlight an urgent need for improved public health initiatives with respect to recognition and treatment of anaphylaxis. We flag key problems that should be managed in the coming years through implementation of national and international actions.' },
      { id: 3, title: 'Description of two anaphylaxis phenotypes in children: The utility of a clustering analysis approach', authors: 'G Pouessel, JC Dubus, S Lejeune, H Béhal, G Noël, E Beaudouin, A Deschildre, J Corriger', abstract: 'No abstract available' },
      { id: 4, title: '[Non-intensive care of COVID-19 patients: treatment plan and therapeutic orientations]', authors: 'J Corriger, C Rein, P Salvadori, AM Villena, G Cinquetti', abstract: 'Despite the recent emergence of COVID-19 and the absence of a specific cure, the hospital treatment of patients affected by this virus is well established. It is based on symptomatic treatments including oxygen therapy, physiotherapy and anticoagulation therapy. The treatment plan and potential therapeutic limitations must be well defined and adapted to the severity, predisposition and wishes of the patient.' },
      { id: 5, title: 'Personalized medicine and food allergies', authors: 'J Corriger, M De Carvalho Bittencourt', abstract: 'Advances in modern biology including omics sciences will landmark a serious change in food allergy practice, leading to a more patient-tailored care. This precision medicine is based on the characterization of biomarkers able to identify at risk people in early disease stages and on the accurate characterization of specific allergic phenotypes and endotypes at individual level and prediction of disease course. A better understanding of these key points will allow an accurate selection of the appropriate treatment for each patient. In the near future, the dissemination of this systemic biology could change the practice of allergology. The aim of this review is to describe the potential uses and benefits for the clinician of precision medicine in food allergy.' },
      { id: 6, title: 'Allergic reaction to calving : A-galactose as a new occupational allergen', authors: 'J Corriger, E Penven, M Lang, H Thomas, V M Nguyen-Grosjean, J Pontier, A Vaillant, E Beaudouin', abstract: 'No abstract available' },
      { id: 7, title: 'Asthma in hairdressing', authors: 'E Penven, J Corriger, I Thaon', abstract: 'No abstract available' },
      { id: 8, title: 'International session: Towards prevention and personalized treatment of food allergies', authors: 'J Corriger, L Pellicer-Garcia, A Valeille, T Adam, J Flabbee', abstract: 'No abstract available' },
      { id: 9, title: 'Cashew nut allergy', authors: 'Q Haumonte, E Beaudouin, V M Nguyen, J Picaud, H Thomas, J Corriger, A Barbaud', abstract: 'The cashew nut is the fruit of Anacardium occidentale, a tree belonging to the Anacardiaceae family, like the pistachio and mango trees (Bois, 1996). Consumption of cashew nuts has risen steadily in recent decades, as attested by the marked increase in worldwide production (http://faostat3.fao.org/home/E). Cashew nut allergy is an emerging disease; it is generally severe and may be fatal (Van der Valk et al., 2014). In Europe, cashew nuts are the fourth leading cause of anaphylaxis amongst food allergens (Grabenhenrich et al., 2016). Diagnosis is currently based upon precise questioning to screen for an evocative clinical history, upon skin tests, and upon assay of allergen-specific immunoglobulin E. Treatment involves withdrawal of cashew nuts but also pistachio nuts (Van der Valk et al., 2014). The purpose of this study is to summarise current knowledge about cashew nut allergy, including botanical data, epidemiological data, the clinical characteristics of allergic populations, cross-reactivity, diagnostic criteria, and current and emerging treatment methods.' },
      { id: 10, title: 'Bilan des consultations bi-disciplinaires de dermato-allergologie professionnelle réalisées au CHRU de Nancy entre 2012 et 2017', authors: 'E Penven, J Corriger, C Poreaux, E Freling, F Brault, F Roch, C Paris, A Barbaud, J L Schmutz, I Thaon', abstract: 'Introduction : Les dermatoses de contact en relation avec le travail (DCRT) sont les affections dermatologiques les plus fréquentes en milieu professionnel dans les pays développés. Leur incidence réelle en population active reste toutefois mal connue, ces affections étant souvent sous-déclarées voire sous-diagnostiquées. Leur impact sur la qualité de vie et le devenir professionnel peut être majeur. Méthodes : Nous rapportons ici une première description des caractéristiques socio-démographiques, médicales et professionnelles des patients adressés au centre de consultation de pathologies professionnelles (CCPP) du CHRU de Nancy pour suspicion de DCRT entre 2012 et 2017. Ces patients ont tous bénéficiés de consultations bi-disciplinaires réalisées conjointement par un médecin du CCPP et un dermatologue, tous deux qualifiés en allergologie. Résultats : Au total, 243 patients âgés de 15 à 61 ans (médiane 33 ans) ont été recensés, dont 53 % de femmes. L’origine de la demande de consultation émanait dans 58 % des cas du médecin du travail, et dans 32 % des cas de médecins spécialistes (dermatologues ou allergologues). Si la majorité des patients avait un statut salarié (84 %), près de 10 % étaient encore en formation (apprentis, scolaires en filière professionnelle). À l’issu du bilan allergologique, si le diagnostic de dermite d’irritation isolée était retenu dans 20 % des cas, 43 % des patients présentaient au moins une sensibilisation documentée à un allergène de l’environnement de travail, les plus fréquemment identifiés étant les persulfates alcalins, la PPD, les acrylates/méthacrylates et les thiurams. Toutes DCRT confondues, les nuisances les plus fréquemment incriminées étaient les produits de coiffure, les produits ménagers, les agents de vulcanisation du caoutchouc et les résines, colles et matières plastiques. Conclusion : Bien souvent multifactorielles, les DCRT surviennent dans des secteurs d’activité et métiers variés, même si la coiffure, les métiers du nettoyage et du soin sont particulièrement touchés. Une évaluation allergologique bi-disciplinaire associant un spécialiste en pathologie professionnelle apparaît essentielle pour orienter au mieux les examens et le devenir professionnel de ces patients.' }
    ];
    return {articles};
  }

  // Overrides the genId method to ensure that an article always has an id.
  // If the articles array is empty, the method below returns the initial number (11).
  // if the articles array is not empty, the method below returns the highest article id + 1.
  genId(articles: Article[]): number {
    return articles.length > 0 ? Math.max(...articles.map(article => article.id)) + 1 : 1;
  }

}
